### ISSUE TITLE
Option To Remove Navigator From Task Manager

### ISSUE THREAD

**Issue by scriptGenie** [dangvd/crystal-dock#11]
Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-10-generic (64-bit)
Graphics Platform: X11

Requested Feature: Ability to unpin 'Navigator'.

Current workaround is to disable 'Task Manager' in 'Optional Features', which removes ability to see running programs that are not pinned.

**Comment by dangvd** [comment]
Sorry what is the Navigator?

**Comment by scriptGenie** [comment]
If I add two launchers to the dock (Firefox, Konsole) I see a third docked application with the Firefox icon, and the tooltip shows 'Navigator'.
![screenshot](https://github.com/dangvd/crystal-dock/assets/130425150/42983791-2046-46fd-8f3c-3e6b13f0483d)

**Comment by scriptGenie** [comment]
Environment Variables: BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/firefox_firefox.desktop
Program: /snap/bin/firefox
Arguments: %u

The firefox_firefox.desktop file is set to open with Konsole.

**Comment by dangvd** [comment]
Should work better now with Crystal Dock v2.0 on Wayland. Please re-open if it's still an issue.
Thanks,
