### ISSUE TITLE
VirtualBox - VMs Not Showing In Dock

### ISSUE THREAD

**Issue by scriptGenie** [dangvd/crystal-dock#12]
Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-10-generic (64-bit)
Graphics Platform: X11
VirtualBox Version: 7.0.10_Ubuntu r158379

Virtual machines are not showing in the dock.  Both 'VirtualBox' and 'VirtualBox Manager' are showing correctly, but VMs show nothing.

**Comment by dangvd** [comment]
Could you please elaborate a bit more? The dock only shows running applications, it doesn't show virtual machines.

**Comment by scriptGenie** [comment]
If I run two virtual machines from the VirtualBox manager application the vms are not displayed on the dock as currently running applications as was the case in KSmoothDock.

**Comment by dangvd** [comment]
Should work better now with Crystal Dock v2.0 on Wayland. Please re-open if it's still an issue.
Thanks,
