### ISSUE TITLE
Add mention that LXQt needs a compositor when using Openbox

### ISSUE THREAD

**Issue by Slater91** [dangvd/crystal-dock#14]
Hello! I started using Crystal Dock on an old MacBook 4,1 running Endeavour OS with LXQt as the desktop environment. I found that the dock displays graphical issues when the window manager is set as Openbox in LXQt: whenever the mouse moves on the dock, there is a black border around it. This is due to Openbox's lack of compositing out of the box.
Although this may seem obvious to more experienced users, I think it would be good to add a small note in the documentation that points this out for users of LXQt who do not know about this (e.g. "Please install a compositor such as Xcompmgr if you use Openbox as your window manager in LXQt").
Thank you and keep up with the great work!

**Comment by dangvd** [comment]
Hi, thanks for that. I will create a FAQs and add this to it.

**Comment by dangvd** [comment]
Added to:
https://github.com/dangvd/crystal-dock/wiki/Documentation#troubleshooting
