### ISSUE TITLE
Be able to control the window like closing

### ISSUE THREAD

**Issue by Dangerise** [dangvd/crystal-dock#15]
In some normal task managers, it's able to do some actions like closing and maximizing by right clicking the icon in the panel, hope the same for the crystal-dock

**Comment by Dangerised** [comment]
Furthermore, it will be nice to be called out when pressing win button

**Comment by dangvd** [comment]
Hi,

KWindowSystem, the library that crystal-dock uses, does not support maximizing/closing actions so I can't do it yet.

Cheers,

**Comment by dangvd** [comment]
Re-opened as I might be able to do this for the next version due to the new library.

**Comment by Dangerised** [comment]
I'm looking forward to it.

**Comment by dangvd** [comment]
Version 2.0 has added Close Window(s) to the context menu.
I did not add Maximize because it depends on the applications -- not all of them want to be maximized e.g. a Music app. I think Windows 11 does not have Maximize option either, probably for the same reason.
