### ISSUE TITLE
Add Activities Support

### ISSUE THREAD

**Issue by ordric** [dangvd/crystal-dock#16]
Would it be possible to add support for activities, so that the pinned icons can change depending on which activity is selected. 

For example, in my 'Work activity' I have: 

Home, Chrome, Thunderbird, Write, Sheets, Impress etc.

When I change to my 'Novel Writing activity' It would automatically change to: 

Home, Chrome, Thunderbird, Typora,  Writing-Aids, Zim Notes etc.

And the same would go for my graphics, programming and music activities.

Would that be possible.

**Comment by dangvd** [comment]
Hi,

It's possible. However, I feel it's a bit duplicate with Virtual Desktop.
What's the difference if you set up 2 Virtual Desktops: Desktop 1 for Work, and Desktop 2 for Novel Writing?

Thanks,
Viet

**Comment by ordric** [comment]
Because I use several virtual desktops per activity, with other configurations which work per activity, that I can't configure per desktop. 

I could use a widget per activity, but they are less configurable and less stable than your dock.

Regards

Jon

**Comment by ordric** [comment]
Thanks... I have been using Ksmoothdock since you started.
Glad you have kept Quiet mode in it.

Regards

Jon

**Comment by dangvd** [comment]
Added in version 2.0
