### ISSUE TITLE
Add edge offset

### ISSUE THREAD

**Issue by ordric** [dangvd/crystal-dock#17]
It would be really useful if you could add an edge-offset function to the dock, so that the dock appears away from the edge selected by the amount in the offset. for example, if I select the left screen edge for the dock and have an offset of 20, the dock appears 20x pixels in from that edge. 

Regards

Jon

**Comment by dangvd** [comment]
You mean, it would be left-aligned with offset from the left edge of the screen?

It would not work well with the parabolic zoom though, as the icons on the right will move away too much and give a bad user experience. The dock really needs to be centered for the parabolic zoom to work well, IMHO.

If you like a left-aligned panel, maybe just use the default desktop panel of your desktop environment?

Thanks,
Viet

**Comment by ordric** [comment]
No, if you have a horizontal panel in the top or bottom centre, with an offset of 20, it wouldn't affect the parabolic zoom, just move it further into the screen. likewise if you have a vertical panel in the left or right centre. 

I would assume if you had a vertical panel in the top or bottom, or a horizontal panel left or right, the offset would be disabled. 

I can't see how that would affect the parabolic zoom.

**Comment by dangvd** [comment]
It's subjective but I think the dock looks better when it's centered in the edge of the screen and offset would make it not as good.

Moreover, this might not even be possible in the next version of Crystal Dock, which will target KDE Plasma 6 and Wayland, because Wayland doesn't allow a window to specify its position.

**Comment by ordric** [comment]
> Moreover, this might not even be possible in the next version of Crystal Dock, which will target KDE Plasma 6 and Wayland, because Wayland doesn't allow a window to specify its position.

That's a bummer!

OK, thanks anyway

Jon

**Comment by 8bitZeta** [comment]
Since this is still open, I believe "floating" is what was being requested here. 

20px being the distance the dock floats off the edge

**Comment by dangvd** [comment]
You might be right that this is about floating. To make it clear, I will create a new bug to replace this one.
Thanks,

**Comment by dangvd** [comment]
The new bug is here: https://github.com/dangvd/crystal-dock/issues/20

**Comment by dangvd** [comment]
Implemented in version 2.1 released today.
