### ISSUE TITLE
Accidentaly Set Max To 40 And Min To 48, Now Crystal Dock Wont Launch (Fixed)

### ISSUE THREAD

**Issue by Noagi6493** [dangvd/crystal-dock#18]
i accidentally set the minimum size to 48 and the maximum size to 40 when i tried to set it to 48, now it does not launch even though i completely reinstalled it, anyone know how to modify the config files?

**Comment by Noagi6493** [comment]
nvm i fixed it somehow

**Comment by dangvd** [comment]
Hi,

Just in case it happens again: the config location is https://github.com/dangvd/crystal-dock/wiki/Documentation#config-location
so you can either remove it (and Crystal Dock will re-generate it), or just edit the config manually in a text editor.

Cheers,
Viet
