### ISSUE TITLE
Multi-screen support

### ISSUE THREAD

**Issue by dangvd** [dangvd/crystal-dock#19]
Multi-screen features (e.g. setting dock on a specific screen) are not yet working.
This will be worked on when I have a multi-screen set up.

**Comment by NotAlexNoyle** [comment]
I am having issues with this, it only lets me set up the panel on one display. Can I send you a screen or something?

**Comment by dangvd** [comment]
Hi,

This issue is open, i.e. not fixed yet.
As noted above, I will work on it when I have a multi-monitor setup (that I don't have at the moment).

**Comment by Shadowedcross** [comment]
Do you have any kind of an ETA? Would love to use this, but it's awkward only having it on one monitor.

**Comment by dangvd** [comment]
Hi,
The next version (v2.2) will be released next week and focus on 3D style.
Then the version after that (v2.3) will focus on this (multi-screen support) and will probably be released in 3 - 4 weeks (so mid - late August).

**Comment by dangvd** [comment]
Hi,

I've had a quick look into this. Unfortunately, on Wayland, I have not found a way to do this.

Specifically, there's no API (Wayland protocol) to set the dock on a specific screen/monitor. Also, on X11, you can simply move the dock to a specific coordinate so that it will be in a specific screen, but on Wayland you can't set the position of the dock (or any window, for that matter) so this does not work either.

**Comment by dangvd** [comment]
Ah I figured it out -- Wayland does support it. Working on it now.

**Comment by dangvd** [comment]
Just a quick note about the timeline: I'm trying to address some critical bugs in v2.3 (in addition to multi-screen support) so it is taking a bit longer than expected -- I'm now aiming for the first half of September for its release.

Sorry about the delay and thanks for your patience.

**Comment by laser73** [comment]
Commit 25a67f7 causes a `Segmentation fault` if there is no screen at (0, 0). This can happen if the top of any screen is above all the other screens.

**Comment by dangvd** [comment]
Thanks a lot for letting me know! I'll fix it.

**Comment by dangvd** [comment]
> Commit [25a67f7](https://github.com/dangvd/crystal-dock/commit/25a67f7f02e41ab1d4bedec7a20eba58b9141013) causes a `Segmentation fault` if there is no screen at (0, 0). This can happen if the top of any screen is above all the other screens.

This has been fixed in this commit:
https://github.com/dangvd/crystal-dock/commit/b9f4af90b166fb0ba3b49eeeb22f0c1a976ccb00

**Comment by dangvd** [comment]
Released in v2.3
