### ISSUE TITLE
Plasma 6 on X11 support

### ISSUE THREAD

**Issue by rodrigopedra** [dangvd/crystal-dock#23]
From my understanding, version 2.0 is focused on Wayland (please correct me if I am wrong)

Will version 1.0 support Plasma 6 on X11?

Or is Plasma 6 on X11 support planned for 2.0?

I need to use some software that doesn't work properly under Wayland

If neither option is planned, that's fine, I just thought of asking as I saw your post on Reddit, and I got interested in this dock

**Comment by rodrigopedra** [comment]
Never mind, I tried compiling v1.0 and it works fine =)

Thanks for this nice dock!

**Comment by dangvd** [comment]
Glad it works and thank you!
