### ISSUE TITLE
Add an option to turn off magnification

### ISSUE THREAD

**Issue by NotAlexNoyle** [dangvd/crystal-dock#29]
Most docks with a zoom feature enable you to turn it off.

**Comment by dangvd** [comment]
Hi,
Thanks for your comment but I'm not sure if it's worth doing. If people don't want the zoom feature, they probably won't use Crystal Dock at all and will just use the default panel that comes with their desktop environment (for example, the default KDE Plasma panel).

**Comment by dangvd** [comment]
This can already be done by setting minimum icon size and maximum icon size (in the Appearance Settings dialog) to the same value.
