### ISSUE TITLE
Incorrect blur effect around the dock window

### ISSUE THREAD

**Issue by astro-angelfish** [dangvd/crystal-dock#38]
There was a giant blur effect around the dock, making my desktop looks terrible. I think it is pretty similar to [this KWin bug](https://bugs.kde.org/show_bug.cgi?id=466227). But not sure if it is the same.

![image](https://github.com/user-attachments/assets/f030d9b4-da72-4b87-89f2-808a3314ed3a)

Environment:
- Operating System: Arch Linux 
- KDE Plasma Version: 6.1.4
- KDE Frameworks Version: 6.5.0
- Qt Version: 6.7.2
- Kernel Version: 6.10.4-arch2-1 (64-bit)
- Graphics Platform: Wayland
- Processors: 12 × Intel® Core™ i5-10400 CPU @ 2.90GHz
- Memory: 15.4 GiB of RAM
- Graphics Processor: Mesa Intel® UHD Graphics 630
- Manufacturer: HASEE Computer
- Product Name: NKx0Sx
- KDE Global Theme: [Blur-Glassy-Light-Global-6](https://www.pling.com/p/2138237/)

**Comment by dangvd** [comment]
Hi,
That big area is the real size of the dock, but it should be transparent if not used (not zoomed in, not displaying tooltip).
Somehow on your system the transparent background didn't work.
Sorry I don't know how to reproduce this yet, but will keep an eye on it.

**Comment by astro-angelfish** [comment]
> Hi, That big area is the real size of the dock, but it should be transparent if not used (not zoomed in, not displaying tooltip). Somehow on your system the transparent background didn't work.
> 
> If you change the Global Theme to some other theme, would it fix it?

Changing between them fixes the problem. But changing back also works fine. I guess it is not related to that KWin issue now.

Restart crystal-dock seems not reproducing the problem either. I'm not gonna try rebooting.

![image](https://github.com/user-attachments/assets/8d541f36-46c4-42a7-964e-3310e8e3aea3)

**Comment by astro-angelfish** [comment]
![image](https://github.com/user-attachments/assets/d47d9e2d-7cc4-495a-b352-c6ed58e431b1)
disabling this in Kvantum settings fixes the problem. Not the fault on crystal-dock or KWin.
