### ISSUE TITLE
Crystal Dock does NOT work in Wayland

### ISSUE THREAD

**Issue by Integral-Tech** [dangvd/crystal-dock#4]
I am using KDE Plasma + Wayland. After opening Crystal Dock, it appears an immobile floating window at the center of the screen. While moving the cursor through the dock, the text above the icon is misplaced. It must be brilliant if you could make it compatible with Wayland :)

**Comment by dangvd** [comment]
Hi, yeah this is a known issue -- this has never worked on Wayland. I've created a tracking feature request to make it clearer #5 

I will try to work on it when I can.

**Comment by dangvd** [comment]
Tracking in #5
