### ISSUE TITLE
Lack of support for X11 makes Crystal Dock useless with LXQt 2.0

### ISSUE THREAD

**Issue by Slater91** [dangvd/crystal-dock#40]
Hello! I was eagerly awaiting for the release of Crystal Dock 2.x, but unfortunately it only works on Wayland. This means it is not usable with LXQt, which only supports X11. I tried using the previous version, 1.0, but it does not work correctly. Since updating to LXQt 2.0, which is based on Qt 6, most applications cannot be pinned to the dock, effectively rendering it useless.

Considering there is no specific timeframe for LXQt to introduce Wayland support, and considering it is going to be experimental at first, this means that I will have to abandon Crystal Dock for an alternative like Plank, which however I would like to avoid. While I understand that this is your project and that you're free to do what you want with it, X11 support is still very much vital, especially if you use older computers with smaller desktop environments or window managers that don't support Wayland (yet, or won't at all). Reintroducing support for X11 would therefore make it possible to use Crystal Dock on a much wider variety of devices. I would therefore encourage you to revisit your decision to drop support for X11.

Thanks!

**Comment by dangvd** [comment]
Hi,

LXQt has mentioned that they will support Wayland in version 2.1 aiming for this autumn: see [link](https://lxqt-project.org/blog/2024/04/15/wayland_faq/). Thus it's probably just a few months away. When it's released I will work on supporting it.

While I agree that ideally Crystal Dock 2.x should support both Wayland and X11, currently I don't have enough free time to do both, unfortunately. Supporting both would also complicate the code base and make it harder to maintain.

**Comment by Slater91** [comment]
Thank you for your answer. I understand that supporting X11 takes time and effort, and I do understand all too well that time is a real concern. Thanks in any case for developing Crystal Dock!
