### ISSUE TITLE
Issue when navigating to left or right edge of dock

### ISSUE THREAD

**Issue by dwconsulting** [dangvd/crystal-dock#44]
Under Fedora, KDE Plasma 6, latest main branch compiled manually

When mousing to the left or right edge of the dock, the following behavior exhibits:
![image](https://github.com/user-attachments/assets/4d5593bd-f37a-4f92-8fb2-0bb4fc357b49)

Normal view, for comparison:
![image](https://github.com/user-attachments/assets/2e64ee3f-0d7c-45b4-a956-b438b170cb94)

**Comment by dangvd** [comment]
Hi,
Sorry to hear this. I noticed you had optional components (Application list, Pager, Clock) disabled. Did this also happen if you had all of them enabled?

**Comment by dwconsulting** [comment]
No worries, it still works :smile: 

I tested enabling each one, one at a time.
Application list: same behavior
Pager: same behavior
Clock: same behavior
All enabled: same behavior

It seems that whatever is leftmost on the dock gets "shoved left" and everything else gets "shoved right". Tried floating and 3d modes, did not change behavior.

I also launched from CLI, only notification I got was:
"QSocketNotifier: Can only be used with threads started with QThread"

Here is what I have for settings:
![image](https://github.com/user-attachments/assets/fcaee38a-fbfc-4936-88e5-2a30d2c5eb5c)

What else can I test or check?

**Comment by dangvd** [comment]
Let me have a look when I have access to my Linux KDE Plasma 6 machine.

**Comment by dangvd** [comment]
Ah I see what you mean, I will look into it.

**Comment by dangvd** [comment]
Fixed in v2.4
