### ISSUE TITLE
Unable to install on Fedora Kinoite

### ISSUE THREAD

**Issue by YKScoding** [dangvd/crystal-dock#46]
On Fedora Kinoite, installing crystal dock using ```rpm-ostree install /path-to-rpm-package/crystal-dock.rpm```, rpm-ostree would fail and give the following error:
```error: Checkout crystal-dock-2.2-1.x86_64: opendir(local): No such file or directory```
![image](https://github.com/user-attachments/assets/5399813f-abd4-4b62-b150-1bdf2b1d293e)
![image](https://github.com/user-attachments/assets/c1b2b059-39e3-4657-9b1f-60d9c63bbbd0)
![image](https://github.com/user-attachments/assets/75560c27-3f30-4f88-9018-9288101469e6)
![image](https://github.com/user-attachments/assets/5e2601bb-ee69-466b-8308-dd71d6c94ace)

**Comment by dangvd** [comment]
Hi,

Sorry to hear that, I think the RPM might not work on Fedora Atomic. It should work on Fedora Workstation 40 though.

**Comment by RedBearAK** [comment]
@dangvd 

>  I think the RPM might not work on Fedora Atomic. It should work on Fedora Workstation 40 though.

FYI, I have been trying the RPM on Fedora 40 (and I think once on Fedora 39 with an earlier release) for a while every time I notice one of the release announcements on Reddit. Unfortunately I've never been able to get it to work well, and for recent releases it won't even start. One of the desktop effects I have enabled dims the screen behind the active window, and when I try to start Crystal Dock the screen dims after a few seconds, so something definitely "starts", but there is nothing visible, nor is there anything that gets revealed when I touch the mouse to the bottom screen edge. 

It would probably be a good idea to put Fedora 41 (beta) KDE spin in a virtual machine and try installing your app there to see what happens. 

The dock looks nice in screenshots, but for now I'm having to stick with a regular Plasma 6 panel on Fedora. On the left side, it shouldn't be capable of interfering with Crystal Dock in any way.

**Comment by dangvd** [comment]
@RedBearAK sorry about that. Could you please start from the command line and see if there's any error printed there?

**Comment by dangvd** [comment]
@ludg1e would need your help here: you are running Crystal Dock on Fedora 40 right? Did you install from source or from the RPM?

**Comment by RedBearAK** [comment]
@dangvd 

```
crystal-dock
QSocketNotifier: Can only be used with threads started with QThread
qt.svg: /usr/share/pixmaps/kando.png:534:6: Could not resolve property: #linearGradient69403
qt.svg: /usr/share/pixmaps/kando.png:534:6: Could not resolve property: #linearGradient39529
Could not find application with id: org.kde.xwaylandvideobridge. The window icon will have limited functionalities.
Could not find application with id: obsidian. The window icon will have limited functionalities.
Could not find application with id: java-lang-Thread. The window icon will have limited functionalities.
```

The screen continues to dim after a few seconds every time I launch it, indicating that KWin believes some new window has the focus and activates the Desktop Effect for the dimming, but nothing is visible on the screen. 

I can "quit" the app with `Ctrl+Q` like any app window. I just can't see it or interact with it. Not appears on the overview screen either. 

You should try it for yourself in a VM. The package names for a manual build are also a bit different from openSUSE, but I don't have much time to look into it right now.

**Comment by ludg1e** [comment]
Hello @dangvd,

I install Crystal Dock under Fedora 40 Workstation (KDE) from the provided RPM at GH releases.
While I know it's an RPM for openSUSE, it works, no issues.

Install log:
```
user@fedora:~/Downloads$ sudo dnf install crystal-dock-2.5-1.x86_64.rpm
Fedora 40 - x86_64 - Updates                      2.3 kB/s | 9.9 kB     00:04
Fedora 40 - x86_64 - Updates                      3.8 MB/s | 4.5 MB     00:01
RPM Fusion for Fedora 40 - Free tainted           8.5 kB/s | 7.8 kB     00:00
RPM Fusion for Fedora 40 - Free tainted           644  B/s | 2.0 kB     00:03
RPM Fusion for Fedora 40 - Free - Updates          18 kB/s | 3.4 kB     00:00
RPM Fusion for Fedora 40 - Free - Updates          50 kB/s |  76 kB     00:01
RPM Fusion for Fedora 40 - Nonfree - Updates      454  B/s | 3.4 kB     00:07
RPM Fusion for Fedora 40 - Nonfree - Updates       48 kB/s |  26 kB     00:00
Dependencies resolved.
==================================================================================
 Package               Architecture    Version        Repository             Size
==================================================================================
Installing:
 crystal-dock          x86_64          2.5-1          @commandline          269 k

Transaction Summary
==================================================================================
Install  1 Package

Total size: 269 k
Installed size: 1.4 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                          1/1
  Installing       : crystal-dock-2.5-1.x86_64                                1/1

Installed:
  crystal-dock-2.5-1.x86_64

Complete!
user@fedora:~/Downloads$
```
![image](https://github.com/user-attachments/assets/a81e3768-ddf6-4668-850e-31bce9559c72)
(the pixelated icons I believe is an issue due to fractional scaling, as I've found to be the cause of issues in other applications)

**Comment by dangvd** [comment]
@ludg1e thanks for the details!

@RedBearAK As ludg1e mentioned, it does work on his Fedora 40. I'm not sure what caused the issue on your system but will keep an eye on it.
