### ISSUE TITLE
After closing windows, their status on the panel remains active, but does not respond to actions.

### ISSUE THREAD

**Issue by sta-zot** [dangvd/crystal-dock#50]
After closing windows, their status on the panel remains active, but does not respond to actions. 

Does not open new instances of the same application. However, applications that have not yet been launched are launched. If you close it, it also becomes pinned and again does not respond to actions with this application.

Updated using the RPM package crystal-dock-2.3-1.x86_64.rpm
`rpm -Uhv crystal-dock-2.3-1.x86_64.rpm`

Updated from version 2.2, I don't remember exactly. The previous version stopped working, every time you click on the application on the panel, a new instance of the application opened

**Comment by dangvd** [comment]
Hi,

Sorry to hear this. Could you please give more info about your system? Distro/Qt/KDE/Plasma version?

I can't reproduce this on mine btw.
