### ISSUE TITLE
CMake Error on Neon

### ISSUE THREAD

**Issue by MedievalMatt** [dangvd/crystal-dock#55]
Hello,

I'm probably just stupid, but I'm trying to build from source in Kde Neon.  I believe I have installed Neon's version of the required packages, but I am getting the following error on entering the CMake command:

    

> CMake Error at CMakeLists.txt:19 (find_package):
>       By not providing "FindLayerShellQt.cmake" in CMAKE_MODULE_PATH this project
>       has asked CMake to find a package configuration file provided by
>       "LayerShellQt", but CMake did not find one.
>     
>       Could not find a package configuration file provided by "LayerShellQt"
>       (requested version 6.0) with any of the following names:
>     
>         LayerShellQtConfig.cmake
>         layershellqt-config.cmake
>     
>       Add the installation prefix of "LayerShellQt" to CMAKE_PREFIX_PATH or set
>       "LayerShellQt_DIR" to a directory containing one of the above files.  If
>       "LayerShellQt" provides a separate development package or SDK, be sure it
>       has been installed.
> 

Obviously the error is a missing configuration file, but I'm not sure why LayerShellQt does not have the necessary file.  Is anyone else attempting to build this on an Ubuntu or Debian-based distro.  If so, what dependencies did you install?

**Comment by dangvd** [comment]
Hi,

It looks like you don't have LayerShellQt6 development package installed.
Could you please double check on that?

Ubuntu/Debian-based distro with KDE Plasma 6 is quite rare at the moment -- you basically have Neon which is not popular as Open SUSE or Fedora. And I personally haven't tried Neon yet.

I may try Kubuntu when the next version is out though.

**Comment by MedievalMatt** [comment]
It looks like there are two dev packages under ubuntu/kubuntu/neon for layershell --  liblayershellqtinterface-dev and libgtk-layer-shell-dev. libgtk-layer-shell-dev is not the package you want.   liblayershellqtinterface-dev is. So I got it to build from source, but I haven't had a chance to start it up and see if it's running yet, as typing in the command says there's another instance running.  I'm going to reboot and see if that clears things.

**Comment by dangvd** [comment]
On Open SUSE there are 2 dev packages for layer-shell, 1 for Qt5 and 1 for Qt6, and one needs to make sure to install the Qt6 version. I'm not sure if it's also the case for Neon?

**Comment by dangvd** [comment]
So from here:
https://packages.debian.org/search?keywords=liblayershellqtinterface-dev&searchon=names&suite=all&section=all
it seems that you have to use the one from experimental branch to support Qt6.

**Comment by dangvd** [comment]
FYI on Kubuntu 24.10 I installed the dependencies with:

```
$ sudo apt install qt6-base-dev libwayland-dev liblayershellqtinterface-dev
```

**Comment by dangvd** [comment]
Latest version (v2.7) now requires:

```
sudo apt install qt6-base-private-dev libwayland-dev liblayershellqtinterface-dev
```
