### ISSUE TITLE
Feature: Allow dock to be positioned On-top of a KDE panel

### ISSUE THREAD

**Issue by marcosilva85** [dangvd/crystal-dock#58]
When Always-on-top is selected, CrystalDock properly goes over app windows (does not need to reserve the space anymore). That's cool.

But if there is a KDE panel at bottom, CrystalDock gets away from panel, as a result we get 2 layers: panel, then CrystalDock. 

Desired: A setting for users that also want dock to go over the kde panel, so it's only 1 layer. This is so we can replace kde's task manager with crystal dock at exact same position in the panel.

**Comment by dangvd** [comment]
Hi,

For this you'll need to change the settings of your KDE panel: either move it to a different position/edge or sets it to Auto Hide or something.

Because if KDE panel requested the window manager to reserve screen space, other applications (e.g. Crystal Dock) won't be able to affect it (for good reasons).

**Comment by marcosilva85** [comment]
from your comment, then  this is technically impossible? too sad if true!
if there would be such a way, it would be really useful for those of us that intend to replace the kde panel widget "icons-only task manager" with crystalDock!


that would be just great, would look good and it would not need to be a kde widget nor implement custom kde widget code on top of that!

**Comment by marcosilva85** [comment]
Yes. if its possible it would be amazing,. Oherwise please let me know just whether its not possible or even if you don't want to try adding it, that's also ok!
But at the moment I'm waiting for this so I could use my horizontal panel with crystalDock over it (replacing the kde "icons-only task manager").

**Comment by dangvd** [comment]
As I mentioned in the post above, the only way to do what you want is to set both Crystal Dock and Plasma panel to Always On Top / Windows Go Below visibility.

**Comment by marcosilva85** [comment]
@dangvd thanks for the reply, I should have added that I considered hide-option but as my laptop is a convertible which can be used fully in tablet mode, most of the times when I am on the go its just so much convenient to have panels always showing to quickly interact in that touch mode.
Hence why I would also prefer crystal-dock over the panel and both visible at once, in same position, and to save vertical / horizontal space.

Hope the use-case is a bit better described and makes sense.

**Comment by dangvd** [comment]
Well as I mentioned, as soon as a panel reserves the desktop space, the other one will be pushed out of that space.
So no, you cannot have 2 panels Always Visible (reserving space) on the same space.

**Comment by dangvd** [comment]
Closing as Won't Fix (Infeasible).
