### ISSUE TITLE
Consider using FPM to create packages for multiple package managers

### ISSUE THREAD

**Issue by bengaywins** [dangvd/crystal-dock#62]
As the title states, use [FPM](https://github.com/jordansissel/fpm) to get your packaging sorted! It was built specifically for this whole consideration because it's not the easiest and it sure ain't simple.

**Comment by dangvd** [comment]
Hi, thanks for your comment.
However, it's not about creating packages, it's about making sure they work. And I think the only way to do so is to install the distros myself and test there. For this reason, I only publish packages for the distros I'm using.

**Comment by bengaywins** [comment]
You can do as many others do and put the packages out there and say that you just don't have the ability to test on anything other than `<distro you use>` and that you'd gladly take contributions to help support others. Imo, it's not so black and white.

**Comment by dangvd** [comment]
New release v2.6 now provides both RPM and DEB binary packages.
