### ISSUE TITLE
Ability to remove rounded corners from "Flat 2D" to get the pre-10.5 look

### ISSUE THREAD

**Issue by WindClan** [dangvd/crystal-dock#75]
I found this dock and hoped it would allow this but it doesn't

Could you please add this?

**Comment by dangvd** [comment]
Hi,

Yeah I could. I think it needs to be a new visual style with the new task indicator as well.
How about this?
![metal_2d](https://github.com/user-attachments/assets/021fb325-5486-4766-8ac3-d39bbc27389c)

We can maybe call this style Metal 2D ?

**Comment by WindClan** [comment]
That looks really good, the only thing is there was a serious lack of padding on the pre-10.5 dock

**Comment by dangvd** [comment]
Right, on Crystal Dock you can already adjust the Icon Spacing Factor in the Appearance Settings dialog for this, but I will reduce the default icon spacing for this Metal 2D style.

**Comment by WindClan** [comment]
Thanks!

**Comment by dangvd** [comment]
Implemented in the main tree. This is how it looks by default:

![metal_2d](https://github.com/user-attachments/assets/f094c8cb-5cc5-4837-b593-09df0d42519a)

**Comment by dangvd** [comment]
Released in v2.6
