### ISSUE TITLE
How can I install this in Kubuntu

### ISSUE THREAD

**Issue by alok-debnath** [dangvd/crystal-dock#77]
Sorry if this is a stupid question but will be glad if someone can help, thanks in advance.

OS: Kubuntu oracular 24.10
DE: KDE Plasma 6.1.5

**Comment by dangvd** [comment]
Hi,

For now, you can compile and install it from the source code. Or if you
could wait for a few days, I'll release a new version soon with a DEB
package, then you'll be able to install from there.

**Comment by alok-debnath** [comment]
> if you could wait for a few days, I'll release a new version soon with a DEB package, then you'll be able to install from there.

Thanks for your work, I will definitely wait for the DEB version

**Comment by dangvd** [comment]
Added in release v2.6
