### ISSUE TITLE
logout  from panel error

### ISSUE THREAD

**Issue by Detritus78** [dangvd/crystal-dock#8]
Great dock! I  have  been looking for a replacement for docky. I just don't like the popular other docks available. Could  easily become my favorite. I have ran into a few issues though. I will post them independently. System info: 
Operating System: MX Linux 23
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.4.11-1-liquorix-amd64 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6600 XT
Manufacturer: NZXT, Inc
Product Name: B550 UD AC

Placing system logout on panel results in this error.

![image](https://github.com/dangvd/crystal-dock/assets/104474321/2c79437c-e961-468f-ba3e-9a10f281c2c5)

**Comment by dangvd** [comment]
Thanks for your support and for letting me know the issues.

About this one: does any of this command work on your console?
qdbus
qdbus-qt5
qdbus6

Thanks,

**Comment by Detritus78** [comment]
qdbus does work, however, the rest of them do not do anything. I also cannot cannot find anything about a Ksmserver on my system nor even in the repo's. 
![image](https://github.com/dangvd/crystal-dock/assets/104474321/c6a1f3fd-e25b-4a10-87c1-edca4f1a27a7)

**Comment by Detritus78** [comment]
I should clarify my original post. Placing the logout on the panel then selecting it causes the error. Not placing it on the panel. It happens on shutdown as well as restart. The only button working properly out of those is the lock screen. Except the issue with logging back in.

**Comment by dangvd** [comment]
Sorry for the delay, so if you type this command into the console, does it work (i.e. logging you out)?
qdbus org.kde.ksmserver /KSMServer logout -1 0 3

**Comment by dangvd** [comment]
Should be fixed in v1.0
