### ISSUE TITLE
Multiple docks on all screens for no apparent reason; I only intentionally made one

### ISSUE THREAD

**Issue by ssteinerx** [dangvd/crystal-dock#94]
I just upgraded to Kubuntu 24.10 with Wayland and Plasma 6.1.

Since Latte, which I had been using, won't work, I'm trying Crystal Dock for the first time.

I got one set up and, for no obvious reason, I now have three.  One on my main display where I put it and two on my other display where I didn't.

There seems to only be one crystal-dock process and quitting any of the docks quits them all.

I can move the extra ones from display 2 to display 1 but that checkbox is a bit flaky and it takes two or three tries to get it to stick.

When I quit and restart, they all come back where I left them, but I only need one...

**Comment by dangvd** [comment]
Hi,

By default, if you have multiple screens, one dock panel will be created for each of them.
However, if you don't like it, just:
right-click -> Panel Settings -> Remove Panel
for the panels you don't want to keep.

In general, with Crystal Dock's support for multiple docks, you can add/remove dock panels as you like.

**Comment by ssteinerx** [comment]
They did go away when I removed the panel, I was more concerned with how they got there in the first place...
